// Code generated by "stringer -type=Button"; DO NOT EDIT.

package listener

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimaryMouseButton-1]
	_ = x[SecondaryMouseButton-2]
	_ = x[MiddleMouseButton-3]
}

const _Button_name = "PrimaryMouseButtonSecondaryMouseButtonMiddleMouseButton"

var _Button_index = [...]uint8{0, 18, 38, 55}

func (i Button) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Button_index)-1 {
		return "Button(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Button_name[_Button_index[idx]:_Button_index[idx+1]]
}
