// Code generated by "stringer -type=ButtonMask"; DO NOT EDIT.

package listener

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrimaryMouseButton-1]
	_ = x[SecondaryMouseButton-2]
	_ = x[MiddleMouseButton-4]
}

const (
	_ButtonMask_name_0 = "PrimaryMouseButtonSecondaryMouseButton"
	_ButtonMask_name_1 = "MiddleMouseButton"
)

var (
	_ButtonMask_index_0 = [...]uint8{0, 18, 38}
)

func (i ButtonMask) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _ButtonMask_name_0[_ButtonMask_index_0[i]:_ButtonMask_index_0[i+1]]
	case i == 4:
		return _ButtonMask_name_1
	default:
		return "ButtonMask(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
