// Code generated by "stringer -type=PointerKind"; DO NOT EDIT.

package listener

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mouse-0]
}

const _PointerKind_name = "Mouse"

var _PointerKind_index = [...]uint8{0, 5}

func (i PointerKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PointerKind_index)-1 {
		return "PointerKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PointerKind_name[_PointerKind_index[idx]:_PointerKind_index[idx+1]]
}
